engines:
  radon:
    enabled: true
    config:
      python_version: 3
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false

ratings:
   paths:
   - "src/*.py"
